announcements.shared.socials.discord=Join our {discord}! {invite_url}
announcements.shared.socials.twitter=Follow us on {twitter} {twitter_handle}
announcements.shared.socials.instagram=Follow us on {instagram} {instagram_handle}
announcements.shared.socials.web=Check out our Forums at {url}
announcements.shared.socials.map_submissions=Want to create a map that could appear on CubeCraft? Submit today: {url}
announcements.shared.socials.discord_spring_comp_26_java=Want to win an Obsidian Subscription? Enter our Spring Competition now. Join our {discord}! {invite_url}
announcements.shared.socials.discord_spring_comp_26_bedrock=Want to win a Game Pass? Enter our Spring Competition now. Join our {discord}! > {url}
announcements.shared.socials.discord_summer_comp_26_java=Want to win an Obsidian Subscription? Enter our Summer Competition now. Join our {discord}! {invite_url}
announcements.shared.socials.discord_summer_comp_26_bedrock=Want to win a Game Pass? Enter our Summer Competition now. Join our {discord}! > {url}

announcements.shared.socials.discord_spring_sale_26_java=There's now 33% Off all Subscriptions on our {store}. Check it out at {store_url}!
announcements.shared.socials.discord_spring_sale_26_bedrock=33% Off All Game Passes check them out in "{passes}" & "{gifts}"!
announcements.shared.socials.discord_summer_sale_26_java=There's now 50% OFF all Subscriptions on our {store}. Check it out at {store_url}!

announcements.shared.moderation.drag_clicking=Drag clicking and double clicking are not allowed. Doing so will result in a cheating ban.

announcements.java.moderation.report=Cheating is against the server rules. You can report rule breakers at {url}
announcements.bedrock.moderation.report=Cheating is against the server rules. You can report rule breakers using {command} or at {url}
announcements.shared.moderation.dont_share_info=NOTICE! Don't join random Discords, share passwords/codes with strangers. You could lose your account! Read more here: {url}
announcements.shared.moderation.player_safety=Stay safe on CubeCraft! Learn about account and user safety here: {url}